name: Publishing to crate.io

on:
  push:
    branches:
      - release

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: install dependencies
        run: |
          sudo apt-get install -y webkit2gtk-4.1-dev javascriptcoregtk-4.1-dev libsoup-3.0-dev libglib2.0-dev libgtk-3-dev libudev-dev  pkg-config

      - name: export pkg config path
        run: export PKG_CONFIG_PATH=/usr/lib/aarch64-linux-gnu/pkgconfig:$PKG_CONFIG_PATH
      - uses: katyo/publish-crates@v2
        with:
          registry-token: ${{ secrets.CARGO_REGISTRY_TOKEN }}
